/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#ebf1ff",
        "on-secondary-fixed-variant": "#214b60",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb4a3",
        "surface-tint": "#436086",
        "on-primary-fixed-variant": "#2a486d",
        "primary": "#244267",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#3f687d",
        "dusk-blue": "#3d5a80",
        "secondary-fixed-dim": "#a3cce4",
        "tertiary": "#7e1b03",
        "on-secondary-fixed": "#001e2b",
        "surface-container-low": "#f0f3ff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffc1b2",
        "secondary-fixed": "#c2e8ff",
        "light-cyan": "#e0fbfc",
        "on-primary-fixed": "#001c39",
        "on-primary-container": "#b4d1fe",
        "powder-blue": "#98c1d9",
        "surface-variant": "#dae3f7",
        "primary-fixed": "#d3e3ff",
        "on-surface-variant": "#43474e",
        "inverse-primary": "#abc8f4",
        "surface-container": "#e7eeff",
        "on-background": "#131c2a",
        "jet-black": "#293241",
        "on-tertiary": "#ffffff",
        "secondary": "#3b6378",
        "tertiary-container": "#9f3319",
        "on-surface": "#131c2a",
        "surface-dim": "#d1daee",
        "tertiary-fixed": "#ffdad2",
        "surface-container-high": "#dfe8fc",
        "surface-container-highest": "#dae3f7",
        "error": "#ba1a1a",
        "outline": "#73777f",
        "outline-variant": "#c3c6cf",
        "primary-fixed-dim": "#abc8f4",
        "burnt-peach": "#ee6c4d",
        "surface-bright": "#f9f9ff",
        "inverse-surface": "#283140",
        "secondary-container": "#bce5fe",
        "background": "#f9f9ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#872108",
        "primary-container": "#3d5a80",
        "on-tertiary-fixed": "#3d0700",
        "surface": "#f9f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "margin": "2rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk"],
        "headline-sm": ["Space Grotesk"],
        "display-lg-mobile": ["Space Grotesk"],
        "body-lg": ["Manrope"],
        "label-lg": ["Manrope"],
        "display-lg": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "label-sm": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-lg-mobile": ["Space Grotesk"],
        "body-sm": ["Manrope"],
        "label-md": ["Manrope"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
